### ISSUE TITLE
Suggestion: Add screenshots to the README

### ISSUE THREAD

**Issue by kbayliss** [zerolab/wagtail-periodic-review#8]
This looks great - thanks for all the work so far! And a big kudos for all the comments and docstrings throughout 😍.

A minor suggestion: I would love to see screenshots in the README that demo the package, as this would make it easier to visualise what it does without reading lots of (lovely) code.

**Comment by zerolab** [comment]
@kbayliss how about now?

**Comment by zerolab** [comment]
added in da3b623
