### ISSUE TITLE
Suggestion: Integrate with Ageing Pages report

### ISSUE THREAD

**Issue by kbayliss** [zerolab/wagtail-periodic-review#9]
Wagtail now comes with an "Aging pages" report (`/admin/reports/aging-pages/`), which feels like it would benefit from integration from this package - i.e. perhaps `wagtail-periodic-review` could add a filter or label/badge to the report list view to identify pages needing review?

**Comment by zerolab** [comment]
We'd need to basically override the Aging pages report. I am not entirely sold on it (yet) due to needing to keep up with any changes to it (all potential, of course)

**Comment by zerolab** [comment]
Having thought more about this, we either:
a. replace the "Aging pages" report
b. do nothing.

Ultimately they serve different purposes, so I say we do nothing. Thank you for the suggestion, though
